my_theme <- function(...) {
  theme(
    axis.line = element_line(color = "black"), 
    axis.text.x = element_text(color = "black", size = 12, lineheight = 0.9),  
    axis.text.y = element_text(color = "black", size = 12, lineheight = 0.9),  
    axis.ticks = element_line(color = "black", size = 0.5),  
    axis.title.x = element_text(color = "black", margin = margin(0, 10, 0, 0), size = 12),  
    axis.title.y = element_text(color = "black", angle = 90, margin = margin(0, 10, 0, 0), size = 12),  
    axis.ticks.length = unit(0.5, "lines"), 
    legend.background = element_rect(color = NULL, fill = "white"),  
    legend.key = element_rect(color = "black",  fill = "white"),  
    legend.key.size = unit(1.2, "lines"),  
    legend.key.height = NULL,  
    legend.key.width = NULL,      
    legend.text = element_text(color = "black"),  
    legend.title = element_text(face = "bold", hjust = 0, color = "black"),  
    legend.text.align = NULL,  
    legend.title.align = NULL,  
    legend.direction = "vertical",  
    legend.box = NULL, 
    # axis.line = element_segment(),
    panel.background = element_rect(fill = NA, color  =  NA),  
    # panel.border =  element_rect(linetype = "solid", fill = NA, color = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.spacing = unit(0.5, "lines"),
    strip.background = element_rect(
      color = "black", fill = "#FF0066", size= 1.5, linetype="solid"),
    strip.text.x = element_text(color = "white"),  
    strip.text.y = element_text(color = "white", angle = -90),  
    plot.background = element_rect(color = "white", fill = "white"),  
    plot.title = element_text(color = "black", hjust = 0.5, lineheight = 1.25,
                              margin = margin(2, 2, 2, 2), face = "bold.italic"),  
    plot.subtitle = element_text(color = "black", hjust = 0, margin = margin(2, 2, 2, 2)),  
    plot.caption = element_text(color = "black", hjust = 0),  
    plot.margin = unit(rep(1, 4), "lines"))
}